server:
 port: 8081
 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security #?connectionTimeZone=UTC #change this to your database url
    password: 1234 #change this to your database username
    username: admin #change this to your database password
  jpa:
    show-sql: true
    hibernate:
      jdbc:
        time_zone: America/Sao_Paulo #To fix wampp server error on Africa's time Zone
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect